server:
  port: 8082
spring:
  application:
    name: farmer-seckill
  datasource:
    url: jdbc:mysql://1.117.249.135:3306/seckill?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 1.117.249.135
    port: 6379
    password: root@123
  freemarker:
    request-context-attribute: rc
    suffix: .html
    enabled: true
    cache: false
    charset: utf-8
    content-type: text/html
    check-template-location: true
    expose-request-attributes: true
    expose-session-attributes: true
    allow-request-override: false
    allow-session-override: false
    template-loader-path: classpath:/templates/
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml